  [build]
  functions = "netlify/functions"

  [[redirects]]
  from = "/about-us"
  to = "/"
  status = 301
  force = false

  [[redirects]]
  from = "/laboratorio-dental"
  to = "/"
  status = 301
  force = false

  [[redirects]]
  from = "/clinica-dental"
  to = "/"
  status = 301
  force = false

  [[redirects]]
  from = "/gastro"
  to = "/"
  status = 301
  force = false
  
  [[redirects]]
  from = "/contact"
  to = "/"
  status = 301
  force = false

  [[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

  [[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  
  [[redirects]]
  from = "/*"
  to = "/templates/404.html"
  status = 404
 